---
- name: Create table dynamodb
  hosts: localhost
  vars:
    ansible_python_interpreter: "/usr/bin/python3.9"
  tasks:
    - name: Create dynamo table with hash and range primary key
      community.aws.dynamodb_table:
        name: my-table
        hash_key_name: id
        hash_key_type: STRING
        range_key_name: create_time
        range_key_type: NUMBER
        read_capacity: 2
        write_capacity: 2
        tags:
          tag_name: tag_value
