---
- name: Listar buckets da AWS
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Coletar informações sobre os buckets do Amazon S3
      community.aws.s3_bucket_info:
      register: s3_buckets

    - name: Exibir os buckets
      debug:
        msg: "Bucket: {{ item.name }}"
      loop: "{{ s3_buckets.buckets }}"
