---
- name: Clone GitHub Repository
  hosts: localhost  # Clonaremos o reposit칩rio na m치quina local
  tasks:
    - name: Clone the GitHub repository
      git:
        repo: https://github.com/yrmenezes79/Cloud_Infrastructure_as_Code
        dest: /root  # Substitua pelo diret칩rio de destino onde deseja clonar o reposit칩rio
