---
- name: Listar arquivos no diretório /tmp de uma instância remota
  hosts: all
  tasks:
    - name: Executar ls no diretório /tmp
      command: ls /tmp
      register: ls_output

    - name: Exibir saída do comando ls
      debug:
        var: ls_output.stdout
