---
- name: Instalação de dependências
  hosts: all
  become: true
  tasks:
    - name: Instalar git
      dnf:
        name: git
        state: present

    - name: Instalar Python 3.9 e pip
      dnf:
        name: python3.9-pip
        state: present

    - name: Instalar boto3 e botocore usando pip3.9
      pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - boto3
        - botocore

    - name: Instalar Ansible Core
      dnf:
        name: ansible-core
        state: present
