---
- name: Instalação do Apache HTTP Server (httpd) no RHEL
  hosts: "{{ target_host }}"
  become: yes

  tasks:
    - name: Instalar o pacote httpd
      package:
        name: httpd
        state: present

    - name: Iniciar o serviço httpd
      service:
        name: httpd
        state: started
        enabled: yes
